### ISSUE TITLE
Half-screen activity like Hangouts profile

### ISSUE THREAD

**Issue by xsorifc28** [saulmm/CoordinatorBehaviorExample#11]
How can I make the activity half screen like the hangouts profile so that the user may scroll down to close the activity or scroll up to continue using the activity?

Thanks in advance!

**Comment by saulmm** [comment]
There are multiple implementations about that, give a look to Plaid -> https://github.com/nickbutcher/plaid, its details views perform a close behavior on scroll

**Comment by xsorifc28** [comment]
Thank you! I've been looking around for something like Plaid.
