### ISSUE TITLE
Why CoordinatorLayout is wrapped with LinearLayout?

### ISSUE THREAD

**Issue by farmazon3000** [saulmm/CoordinatorBehaviorExample#23]
https://github.com/saulmm/CoordinatorBehaviorExample/blob/master/app/src/main/res/layout/activity_main.xml

**Comment by wilsonssss** [comment]
There are no reasons, try to remove LinearLayout.

**Comment by saulmm** [comment]
You were right, just removed. Thanks!

**Comment by farmazon3000** [comment]
So where is it fixed (in which commit)?

**Comment by saulmm** [comment]
Here it is -> c6b3d22f53fa0754a3d116795346f558895b74d1
