### ISSUE TITLE
How to make this type of layout ?

### ISSUE THREAD

**Issue by Kavan72** [saulmm/CoordinatorBehaviorExample#33]
![ktzxp](https://cloud.githubusercontent.com/assets/19048640/22960211/09ae4790-f362-11e6-905a-d874298da6f3.png)

**Comment by judemanutd** [comment]
Have a look at this file [https://github.com/saulmm/CoordinatorExamples/blob/master/app/src/main/res/layout/activity_material_up_concept.xml#L1](activity_material_up_concept.xml)

**Comment by saulmm** [comment]
Yep, first, sorry for the delay on my answer. I think that [this one](https://github.com/saulmm/CoordinatorExamples/blob/master/app/src/main/res/layout/activity_simple_coordinator.xml#L51) fits better than the @judemanutd proposed layout, but changing the `NestedScrollView` by a `RecyclerView` with a scrollable behavior
