### ISSUE TITLE
Getting an error while running this project.

### ISSUE THREAD

**Issue by ravi9598** [saulmm/CoordinatorBehaviorExample#41]
Caused by: android.view.InflateException: Binary XML file line #0: Could not inflate Behavior subclass saulmm.myapplication.AvatarImageBehavior.

**Comment by carlosfpj** [comment]
I have the same mistake, but i presume we have to compile some 'com.something.somethingelse' file in the gradle, but i dont know what exactly

**Comment by carlosfpj** [comment]
Found it ravi, put your apppackage.yourclassAvatarImageBehavior in the attribute app:layout_behavior, and it will work

**Comment by ravi9598** [comment]
thanks
