### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by EpsilonOrionis** [saulmm/CoordinatorBehaviorExample#8]
I'm including a custom layout into the CardView, but it's short and when I scoll the view, I get a wide void space between the toolbar and the CardView. Could you block the animation when the scrolling is terminated?

Thanks in advance

P.S: Sorry for my bad English.

**Comment by nishantBabaria** [comment]
Add  android:clickable="true" to CardView For Scrolling Like Google Play Profile 

<android.support.v7.widget.CardView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_margin="8dp"
                app:cardElevation="8dp"
                app:contentPadding="16dp" 
                 android:clickable="true"
                >

**Comment by MedoElkamaly** [comment]
great @nishantBabaria it works like a charm :+1:

**Comment by saulmm** [comment]
There is a new `layout_scrollFlag` that animates the `AppbarLayout` from an specific percentage of scroll, I can't reproduce that bug, could you @EpsilonOrionis check now with the new support libraries version?

Thanks!

**Comment by EpsilonOrionis** [comment]
The problem is still alive

**Comment by saulmm** [comment]
@EpsilonOrionis could you take a video of the bug to check what's happening?

**Comment by EpsilonOrionis** [comment]
I don't think it's a bug. You can try it. You have to make the CardView shorter, for example with a short word in the TextView inside it. Try to scroll and look what happens... It's wrong. It should block the scroll when the hole CardView and thus it's content is fully visible.

**Comment by EpsilonOrionis** [comment]
Please answer...

**Comment by saulmm** [comment]
@EpsilonOrionis sorry for the delay, will give you an answer soon ;)

**Comment by EpsilonOrionis** [comment]
Ok, thank you :)

**Comment by saulmm** [comment]
I saw your bug, will take care in a new release
