### ISSUE TITLE
Layout Not Support For Tablet

### ISSUE THREAD

**Issue by nishantBabaria** [saulmm/CoordinatorBehaviorExample#9]
CoordinatorLayout Not Supported for Tablet Layout

![screenshot_2015-09-08-12-12-54](https://cloud.githubusercontent.com/assets/5509322/9728099/500748b4-5623-11e5-93f9-570e27bfb2cd.png)

**Comment by saulmm** [comment]
Thanks @nishantBabaria I'll implement tablet support soon!

**Comment by staz1000** [comment]
I have the same layout issue on a tablet, I'd love a fix for this!

**Comment by davcpas1234** [comment]
I fixed this through changing `AvatarImageBehaviour.java` line 87:

```java
- mStartYPosition = (int) (child.getY() + (child.getHeight() / 2));
+ mStartYPosition = (int) (dependency.getY());`
```
